version: '3.8'

services:
  # BioAPI Service
  bioapi:
    image: isongjosiah/protchain:bioapi
    container_name: bioapi
    ports:
      - "8000:8000"
    environment:
      - BIOAPI_ENV=local
    networks:
      - protchain-network

  # Protchain API
  protchain-api:
    image: isongjosiah/protchain:protchain-api
    container_name: protchain-api
    ports:
      - "8001:8001"
    environment:
      - API_ENV=local
      - BLOCKCHAIN_URL=grpc://peer0.org1.example.com:7051
      - BIOAPI_URL=http://bioapi:8000
    depends_on:
      - bioapi
    networks:
      - protchain-network

networks:
  protchain-network:
    driver: bridge
