test:
  name: "Protein Metadata Benchmark"
  description: "Benchmarking throughput & latency for protein metadata chaincode"
  workers:
    number: 2           # number of Caliper client processes

  rounds:
    - label: "Store 100"
      txNumber: 1000    # total transactions to send
      rateControl:
        type: fixed-rate
        opts:
          tps: 100      # send 100 transactions per second
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0       # 0 = no time limit, rely on txNumber

    - label: "Store 200"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store 300"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store 400"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store 500"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store(2) 100"
      txNumber: 2000    # total transactions to send
      rateControl:
        type: fixed-rate
        opts:
          tps: 100      # send 100 transactions per second
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0       # 0 = no time limit, rely on txNumber

    - label: "Store(2) 200"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store(2) 300"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store(2) 400"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0

    - label: "Store(2) 500"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-store.js"
      duration: 0


    - label: "Query 100"
      txNumber: 1000    # total transactions to send
      rateControl:
        type: fixed-rate
        opts:
          tps: 100      # send 100 transactions per second
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0       # 0 = no time limit, rely on txNumber

    - label: "Query 200"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query 300"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query 400"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query 500"
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query(2) 100"
      txNumber: 2000    # total transactions to send
      rateControl:
        type: fixed-rate
        opts:
          tps: 100      # send 100 transactions per second
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0       # 0 = no time limit, rely on txNumber

    - label: "Query(2) 200"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query(2) 300"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 300
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query(2) 400"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 400
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0

    - label: "Query(2) 500"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 500
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload-query.js"
      duration: 0
  
caliper:
  blockchain: "fabric"
  sutOptions:
    connectionProfile: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/networks/fabric-network.yaml"
    # We'll specify the identity we want to use:
    clientCredential: "Org1"
  # Generate an HTML report (also CSV or JSON if you prefer)
  monitors:
    resource:
    - module: docker
      options:
        interval: 5
        containers:
          - peer0.org1.example.com
          - peer0.org2.example.com
          - orderer.example.com
        charting:
          bar:
            metrics: [Memory(avg), CPU%(avg)]
          polar:
            metrics: [all]
    transaction:
    - module: logging
  report:
    type: "html"
    destination: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/report/"
    name: "protein-benchmark-report"
