test:
  name: "Protein Metadata Benchmark"
  description: "Benchmarking throughput & latency for protein metadata chaincode"
  workers:
    number: 2           # number of Caliper client processes

  rounds:
    - label: "Open Loop TPS=100"
      txNumber: 1000    # total transactions to send
      rateControl:
        type: fixed-rate
        opts:
          tps: 100      # send 100 transactions per second
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload.js"
      duration: 0       # 0 = no time limit, rely on txNumber

    - label: "Open Loop TPS=200"
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 200
      workload:
        module: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/benchmarks/protein-workload.js"
      duration: 0

caliper:
  blockchain: "fabric"
  sutOptions:
    connectionProfile: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/networks/fabric-network.yaml"
    # We'll specify the identity we want to use:
    clientCredential: "Org1"
  # Generate an HTML report (also CSV or JSON if you prefer)
  report:
    type: "html"
    destination: "/Users/konig/go/src/github.com/isongjosiah/hack/protchain-project/protchain/blockchain/benchmark/report/"
    name: "protein-benchmark-report"
